#ifndef __hdnesPackEditorimageDialog__
#define __hdnesPackEditorimageDialog__

/**
@file
Subclass of imageDialog, which is generated by wxFormBuilder.
*/

#include "mainForm.h"
#include "imageDialogClient.h"

//// end generated include

/** Implementing imageDialog */
class hdnesPackEditorimageDialog : public imageDialog
{
	protected:
		// Handlers for imageDialog events.
		void imageSelected( wxCommandEvent& event );
	public:
		/** Constructor */
		hdnesPackEditorimageDialog( wxWindow* parent );
	//// end generated class members

        imageDialogClient* clientObj;

        void setClient(imageDialogClient* c);

};

#endif // __hdnesPackEditorimageDialog__
