#ifndef __hdnesPackEditornewProjectDialog__
#define __hdnesPackEditornewProjectDialog__

/**
@file
Subclass of newProjectDialog, which is generated by wxFormBuilder.
*/

#include "mainForm.h"

//// end generated include

/** Implementing newProjectDialog */
class hdnesPackEditornewProjectDialog : public newProjectDialog
{
	protected:
		// Handlers for newProjectDialog events.
		void fileSelected( wxCommandEvent& event );
	public:
		/** Constructor */
		hdnesPackEditornewProjectDialog( wxWindow* parent );
	//// end generated class members


};

#endif // __hdnesPackEditornewProjectDialog__
