#ifndef __hdnesPackEditorcolourSelectDialog__
#define __hdnesPackEditorcolourSelectDialog__

/**
@file
Subclass of colourSelectDialog, which is generated by wxFormBuilder.
*/

#include "mainForm.h"

//// end generated include
#include "colourDialogClient.h"

/** Implementing colourSelectDialog */
class hdnesPackEditorcolourSelectDialog : public colourSelectDialog
{
	protected:
		// Handlers for colourSelectDialog events.
		void colourSelectInit( wxInitDialogEvent& event );
		void colourRClick( wxMouseEvent& event );
		void colourLClick( wxMouseEvent& event );
	public:
		/** Constructor */
		hdnesPackEditorcolourSelectDialog( wxWindow* parent );
	//// end generated class members
        wxPanel* colourPanels[64];
        colourDialogClient* clientObj;
        void setClientObj(colourDialogClient* obj);
};

#endif // __hdnesPackEditorcolourSelectDialog__
