#ifndef __dlgInputImp__
#define __dlgInputImp__

/**
@file
Subclass of dlgInput, which is generated by wxFormBuilder.
*/

#include "mainFrame.h"

//// end generated include

/** Implementing dlgInput */
class dlgInputImp : public dlgInput
{
	public:
		/** Constructor */
		dlgInputImp( wxWindow* parent );

		void showInputDialog( wxActivateEvent& event );
	//// end generated class members

};

#endif // __dlgInputImp__
