#ifndef __frmWaitInputImp__
#define __frmWaitInputImp__

/**
@file
Subclass of frmWaitInput, which is generated by wxFormBuilder.
*/

#include "mainFrame.h"

//// end generated include

/** Implementing frmWaitInput */
class frmWaitInputImp : public frmWaitInput
{
	public:
		/** Constructor */
		frmWaitInputImp( wxWindow* parent );
	//// end generated class members
	
};

#endif // __frmWaitInputImp__
