#ifndef __mainFrameImp__
#define __mainFrameImp__

/**
@file
Subclass of mainFrame, which is generated by wxFormBuilder.
*/

#include "mainFrame.h"

//// end generated include

/** Implementing mainFrame */
class mainFrameImp : public mainFrame
{
	protected:
		// Handlers for mainFrame events.
		void startGame( wxCommandEvent& event );
	public:
		/** Constructor */
		mainFrameImp( wxWindow* parent );
	//// end generated class members
	
};

#endif // __mainFrameImp__
