#ifndef __mainFrameImp__
#define __mainFrameImp__

/**
@file
Subclass of mainFrame, which is generated by wxFormBuilder.
*/

#include "../classList.h"
#include "mainFrame.h"
#include "../gameManager.h"

//// end generated include

/** Implementing mainFrame */
class mainFrameImp : public mainFrame
{
	protected:
		// Handlers for mainFrame events.
		void startGame( wxCommandEvent& event );
        void romSelected( wxFileDirPickerEvent& event );
        void stateSlotSelected( wxCommandEvent& event );
        void rotateSlotSelected( wxCommandEvent& event );
	public:
		/** Constructor */
		mainFrameImp( wxWindow* parent );
	//// end generated class members

        gameManager* gm;

        void updateDisplay();
};

#endif // __mainFrameImp__
